       version: '2'
       services:
         #######################################
         # PHP application Docker container
         #######################################
         app:
           build:
             context: .
             dockerfile: Dockerfile
           links:
             - mysql
             #- postgres
             - solr
           hostname: local.typo3.org
           ports:
             - "8000:80"
             - "8443:443"
             - "10022:22"
           volumes:
             - ./app/:/app/
             - ./:/docker/
           # cap and privileged needed for slowlog
           cap_add:
             - SYS_PTRACE
           privileged: true
           env_file:
             - etc/environment.yml
             - etc/environment.development.yml
           environment:
             - VIRTUAL_HOST=local.typo3.org
             - VIRTUAL_PORT=80
             - POSTFIX_RELAYHOST=[mail]:1025


         #######################################
         # MySQL server
         #######################################
         mysql:
           build:
             context: docker/mysql/
             #dockerfile: MySQL-5.5.Dockerfile
             dockerfile: MySQL-5.6.Dockerfile
             #dockerfile: MySQL-5.7.Dockerfile
             #dockerfile: MariaDB-5.5.Dockerfile
             #dockerfile: MariaDB-10.Dockerfile
             #dockerfile: Percona-5.5.Dockerfile
             #dockerfile: Percona-5.6.Dockerfile
             #dockerfile: Percona-5.7.Dockerfile
           ports:
             - 13306:3306
           volumes:
             - mysql:/var/lib/mysql
           env_file:
             - etc/environment.yml
             - etc/environment.development.yml

         #######################################
         # PostgreSQL server
         #######################################
         #postgres:
         #  build:
         #    context: docker/postgres/
         #    dockerfile: Postgres-9.4.Dockerfile
         #    dockerfile: Postgres-9.5.Dockerfile
         #  ports:
         #    - 15432:5432
         #  volumes:
         #    - postgres:/var/lib/postgresql/data
         #  env_file:
         #    - etc/environment.yml
         #    - etc/environment.development.yml

         #######################################
         # Solr server
         #######################################
         solr:
           image: webdevops/typo3-solr:6.0
         #  image: webdevops/typo3-solr:5.0
         #  image: webdevops/typo3-solr:4.0
         #  image: webdevops/typo3-solr:3.1
           ports:
             - 18983:8983
           volumes:
             - solr:/opt/solr/server/solr/data
           env_file:
             - etc/environment.yml
             - etc/environment.development.yml
           environment:
             - VIRTUAL_HOST=local-solr.typo3.org
             - VIRTUAL_PORT=8983

         #######################################
         # Tika server
         #######################################
         tika:
           build:
             context: docker/tika/
           ports:
             - 19998:9998

         ######################################
         # CI
         ######################################
         ci:
           # We use the travis php container since the we have php, java & mysql later we could use single containers for that for ci
           # https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally
           image: travisci/ci-garnet:packer-1512502276-986baf0
           command: /sbin/init
           volumes:
             - ./bin/:/opt/scripts/
             - ./app/:/app/
             - ./:/docker/
           env_file:
             - etc/environment.yml
             - etc/environment.development.yml
       volumes:
         mysql:
         postgres:
         solr:

